OPENAI_API_KEY="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"
app_password="cem2025"
